### ISSUE TITLE
"./hack/update-codegen.sh" does not work

### ISSUE THREAD

**Issue by vincent-pli** [knative-sandbox/sample-controller#426]
Caused by the issue in `knatiive/hack`: https://github.com/knative/hack/issues/63

I hope we can update the version of `knative/hack` after the issue is gone, thanks

**Comment by jmcshane** [comment]
just ran into this myself cloning this repo and trying to build the code here.

Would love to get this working

**Comment by dprotaso** [comment]
I believe this is resolved see the linked PR in the original post
