### ISSUE TITLE
Infinite empty conditions

### ISSUE THREAD

**Issue by imjasonh** [knative-sandbox/sample-controller#435]
Steps to reproduce

```
git clone https://github.com/knative-sandbox/sample-controller && cd sample-controller/
KO_DOCKER_REPO=kind.local ko apply -f config/
ko apply -f example-addressable-service.yaml
kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml
```

results in:
```yaml
...
spec:
  serviceName: webhook
status:
  address:
    url: http://webhook.knative-samples.svc.cluster.local
  conditions:
  - {}
  - {}
  - {}
  - {}
...
```

It seems to constantly re-add a new empty condition:

```
$ kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml | wc -l
     377
$ kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml | wc -l
     381
```

...and so on.

**Comment by imjasonh** [comment]
This reproduces for me going back as far as `release-0.19`, it might reproduce even further back.

I'm testing against a KinD cluster (`kind v0.10.0 go1.15.7 darwin/amd64`)

**Comment by dprotaso** [comment]
confirmed!

/kind bug

**Comment by dprotaso** [comment]
Schema is missing properties so it's being pruned and we're not clearing that empty condition but adding a new one

https://github.com/knative-sandbox/sample-controller/blob/b4988c7fd71e83064981a712a66cc6d15a6097ae/config/300-addressableservice.yaml#L57-L61

**Comment by imjasonh** [comment]
Nice! I can confirm https://github.com/knative-sandbox/sample-controller/compare/main...imjasonh:fix-crd fixes it. It'd be great to have CRD YAML generation included in the sample and up-to-date so this doesn't happen for repos that fork and modify the template (or, slightly worse, `x-kubernetes-preserve-unknown-fields: true` 😢 )

**Comment by dprotaso** [comment]
There’s a generator in cmd - when I ran it the descriptions were bad lol

But you have to copy and paste - Markus did the latest schema gen stuff for
serving I think it’ll trickle it’s way here

**Comment by dprotaso** [comment]
@markusthoemmes do you know if `controller-gen` (vanilla) work out of the box with this repo?

**Comment by markusthoemmes** [comment]
I believe not. The `URL` type might throw it off.
