### ISSUE TITLE
Failing Releasability check in forked repos

### ISSUE THREAD

**Issue by imjasonh** [knative-sandbox/sample-controller#438]
If you fork and use sample-controller as a template, the repo includes a Releasability check, configured [here](https://github.com/knative-sandbox/sample-controller/blob/main/.github/workflows/knative-releasability.yaml).

I believe the intention of this check is to tell Knative releng whether the sample repo is ready to be released, even though it doesn't seem to have any [releases](https://github.com/knative-sandbox/sample-controller/releases) or [tags](https://github.com/knative-sandbox/sample-controller/tags), only [`release-*` branches](https://github.com/knative-sandbox/sample-controller/branches).

In any case, this Releasability check gets propagated to forked repos, where the check always fails, due to [`buoy exists go.mod --release ${RELEASE} --verbose || EXISTS=$?`](https://github.com/knative-sandbox/sample-controller/blob/de7421903ff1928cfeb1920dbd55bfefe54c1dde/.github/workflows/knative-releasability.yaml#L72). As a consumer of the sample repo template I don't know what that check is supposed to accomplish. From logs it looks like it's checking whether my fork has a `release-0.22` branch.

I understand why Knative releng wants to make sure the sample repo is up-to-date and releasable, I wonder if there's some way to filter out that file from templates, or to disable it by default. Perhaps in the instructions for modifying the repo after forking the template, there should be some step to delete knative-releasability.yaml in your fork.

**Comment by dprotaso** [comment]
cc @knative-sandbox/productivity-wg-leads
