### ISSUE TITLE
Wire up a schema generator

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/sample-controller#470]
Right now our example CRD schemas were generated once and maintained by hand. Ideally we'd introduce a CRD schema generator in one of the `hack/` scripts and provide documentation on how it works

**Comment by mattmoor** [comment]
I see `./cmd/schema`, is this done @dprotaso ?

**Comment by dprotaso** [comment]
sorta - the tool doesn't update the CRD definition automatically so it's partially there
